id: P006953
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10720
  title: གསུང་འབུམ། འཇམ་དབྱངས་འཕྲིན་ལས། ༼དབུས་པར།༽
  author: ''
  volumes:
    f876c65b5155425a85ad3bdb05a8c27b:
      image_group_id: I1KG10722
      title: ''
      volume_number: 1
      total_pages: 665
    c9728500a7624fff95979b14fd7285fc:
      image_group_id: I1KG10723
      title: ''
      volume_number: 2
      total_pages: 672
    e77cfae4116b4854b31e65df447956ef:
      image_group_id: I1KG10724
      title: ''
      volume_number: 3
      total_pages: 704
    65c127357abf478e806cf12ba9c4e906:
      image_group_id: I1KG10725
      title: ''
      volume_number: 4
      total_pages: 692
    9941f922600a4086a6584e4609ce849c:
      image_group_id: I1KG10726
      title: ''
      volume_number: 5
      total_pages: 652
    7847834ea4d8413588864423699ec53e:
      image_group_id: I1KG10727
      title: ''
      volume_number: 6
      total_pages: 762
    6b94dc75e5914379b5f218eef346681d:
      image_group_id: I1PD153371
      title: ''
      volume_number: 7
      total_pages: 722
ebook_metadata:
  title: གསུང་འབུམ། འཇམ་དབྱངས་འཕྲིན་ལས། ༼དབུས་པར།༽
  author: ''
  sku: P006953
  cover: cover.jpg
  layers:
  - pagination
