id: I64ABE17E
legacy_id: P006953
ocr_import_info:
  bdrc_scan_id: W1KG10720
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T02:38:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:48:41.285413+00:00'
last_modified: 2022-08-31 10:54:15.678179
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10720
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10720
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇམ་དབྱངས་འཕྲིན་ལས། ༼དབུས་པར།༽
  author: ཐོ་ཡོན་འཇམ་དབྱངས་འཕྲིན་ལས།
statistics:
  ocr_word_mean_confidence_index: 0.6108497598671683
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1KG10726:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10726
      total_pages: 652
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG10726.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6326215079012446
    legacy_id: v005
  I1KG10722:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10722
      total_pages: 665
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10722.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5463660206973955
    legacy_id: v001
  I1KG10723:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10723
      total_pages: 672
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10723.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6358111343823692
    legacy_id: v002
  I1KG10725:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10725
      total_pages: 692
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG10725.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6253626051882903
    legacy_id: v004
  I1PD153371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD153371
      total_pages: 722
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1PD153371.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5941874578413977
    legacy_id: v007
  I1KG10727:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10727
      total_pages: 762
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG10727.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6323810279621779
    legacy_id: v006
  I1KG10724:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10724
      total_pages: 704
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG10724.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6099777739961283
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
