id: I64ABE17E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:44:47+00:00'
last_modified: '2022-06-08T12:54:00.007243+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10720
  title: གསུང་འབུམ། འཇམ་དབྱངས་འཕྲིན་ལས། ༼དབུས་པར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5C11:
      image_group_id: I1KG10722
      title: Volume 1 of dkyil chog nor bu'i phreng ba/ (dbus par/)
      total_pages: 665
      order: 1
      base_file: 5C11.txt
    63AB:
      image_group_id: I1KG10723
      title: Volume 2 of dkyil chog nor bu'i phreng ba/ (dbus par/)
      total_pages: 672
      order: 2
      base_file: 63AB.txt
    F4C1:
      image_group_id: I1KG10724
      title: Volume 3 of dkyil chog nor bu'i phreng ba/ (dbus par/)
      total_pages: 704
      order: 3
      base_file: F4C1.txt
    '3119':
      image_group_id: I1KG10725
      title: Volume 4 of dkyil chog nor bu'i phreng ba/ (dbus par/)
      total_pages: 692
      order: 4
      base_file: 3119.txt
    8C8D:
      image_group_id: I1KG10726
      title: Volume 5 of dkyil chog nor bu'i phreng ba/ (dbus par/)
      total_pages: 652
      order: 5
      base_file: 8C8D.txt
    82A0:
      image_group_id: I1KG10727
      title: Volume 6 of dkyil chog nor bu'i phreng ba/ (dbus par/)
      total_pages: 762
      order: 6
      base_file: 82A0.txt
    AE35:
      image_group_id: I1PD153371
      title: ''
      total_pages: 722
      order: 7
      base_file: AE35.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
